version: 2
updates:
  # Monitor Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
  # Monitor Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
  # Monitor Python test dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
